### ISSUE TITLE
如何使用 Postman 获取 access token

### ISSUE THREAD

**Issue by yagehu** [Authing/learn#2]
测试 API 经常会用 Postman。如何在 Postman Collection 里面获取 access token？

**Comment by yagehu** [comment]
`<app>.authing.cn/login`

**Comment by yelexin** [comment]
请问需要获取什么 access token？
以下是获取 OIDC token 在 postman 中的配置
![image](https://user-images.githubusercontent.com/27125445/72675821-e0ef4680-3ac4-11ea-9ba7-b1cd0f7a3fa9.png)

**Comment by yagehu** [comment]
谢谢，我是这样获取 oauth2 access token 的：

![Screenshot from 2020-01-19 11-20-27](https://user-images.githubusercontent.com/6758045/72686901-e2614480-3aad-11ea-8800-b4432080f767.png)
